name: "💡 Request Tutorial"
description: Create a new ticket for a new tutorial request.
title: "💡 [REQUEST] - <title>"
labels: [
"feature"
]
body:
- type: textarea
  id: summary
  attributes:
    label: "Summary"
    description: Provide a brief explanation of the tutorial.
    placeholder: Describe in a few lines your tutorial request.
  validations:
    required: true
- type: textarea
  id: basic_example
  attributes:
    label: "Basic Example"
    description: Indicate here some basic examples of your requested tutorial.
    placeholder: A few specific words about your tutorial request.
  validations:
    required: false